---

Information/Sharing:
    - 
        logo: cck.jpg
        title: CCKOREA
        description: CC KOREA is a non-profit organisation that pursues an open culture where everyone gets together to create and share. While respecting the rights of copyright holders, the organisation distributes the CCL(creative commons license), and open license for the sharing of knowledge, information, and art. Since 2013, CC KOREA has been operating SHARE HUB (sharehub.kr) with the Seoul Metropolitan Government to disseminate the culture of sharing. CC KOREA plays an important role in the private sector as Seoul’s partner in realizing &#39;Sharing Seoul&#39;.
        homepage: http://www.cckorea.org/
    - 
        logo: cinegg.jpg
        title: Cinegg
        description: Cinegg set its mission as excaving sustainable alternative independent films and through that promote the diverse independent films and practice community art film screenings and various cultural sharing actions.
        homepage: http://www.facebook.com/cinegg
    - 
        logo: aud.jpg
        title: AUD Social Cooperative
        description: AUD provides plattform for sharing real-time subtitles, applied to not only people who can not hear as well as to all people.
        homepage: http://www.facebook.com/audsc
    - 
        logo: xvision.gif
        title: XVision Technology
        description: Software development company, specializing for visually impaired people, XVision Technology develops smartphone applications to provide comparable information for visually impaired and non-disabled as well.
        homepage: http://www.xvtech.com

Space/Sharing:
    -
        logo: fair.jpg
        title: Fair Space
        description: Liaison for linking idle space to those who need space, including empty café during daytime and empty conference room of a business during  evening hours
        homepage: http://spacemarket.kr/
    -
        logo: idelelot.jpg
        title: Idelelot
        description: Liaison for linking idle space to those who need space, including empty café during daytime and empty conference room of a business during evening hours
        homepage: http://idlelot.kr/
    -
        logo: bnb_hero.jpg
        title: BnBHero
        description: BnB Hero provides a short-term room rental service to travelers. While BnBHero is as easy to use as a hotel, it also provides cheap services and opportunities to interact with local residents. 
        homepage:  http://www.bnbhero.com/
    -
        logo: hanintel.jpg
        title: Hanintel
        description: Liaison for empty rooms for renting to foreign tourists
        homepage:  http://www.hanintel.com/
    -
        logo: homestay_korea.jpg
        title: Home Stay Korea
        description: Liaison for empty rooms for renting to foreign tourists
        homepage:  http://www.homestaykorea.com/
    -
        logo: kozaza.jpg
        title: Kozaza
        description: Kozaza provides travelers deep sleep as well as special experiences by connecting them with empty rooms. In particular, Kozaza has been focusing on ‘hanok stays’ which enable travellers to stay in Korean traditional houses(hanok) and experience traditional culture of Korea.
        homepage:  http://www.kozaza.com/
    -
        logo: labo.jpg
        title: Labo Korea
        description: Liaison for empty rooms for renting to foreign tourists
        homepage: http://www.labo.or.kr/
    -
        logo: modu_parking.jpg
        title: Parking Lot Sharing
        description: Moducompany connects parking lot owners with people who need a parking space during idle time through the smartphone application ‘Modu’s Parking Lot’. Modu’s Parking Lot has proved that parking lot expansion is not the only solution to the city’s serious parking problem. 
        homepage:  http://blog.parkingshare.kr/
    -
        logo: sellpark.jpg
        title: Sellpark
        description: Sellpark shares parking spaces during those times when their owners aren’t using them by its website or application so that people in urgent need of a space can use the parking spaces instead. Users can search for the closest and cheapest available parking space around their office or home using Sellpark.
        homepage: http://www.sellpark.kr/
    -
        logo: space_noah.jpg
        title: Space Noah
        description: Support for office space sharing or co-working network among businesses
        homepage:  http://www.spacenoah.net/
    -
        logo: onoffmix.jpg
        title: On Off Mix
        description: Platform for sharing knowledge and contents. onoffmix is a platform that provides space for events. ONOFFMIX is a platform that provides spaces for events.The company not only provides event information, but also helps with the hosting of events. This service enables easy sharing of knowledge and contents.
        homepage: http://www.onoffmix.com/
    -
        logo: ilsang.jpg
        title: Living and Art Creative Center
        description: Sharing space for living or creative work, education for creation in life
        homepage: http://www.livingnart.or.kr/
    -
        logo: munhwaro.jpg
        title: Norizzang
        description: Sharing workspace or tools to allow people to make daily necessities by recycling waste wood
        homepage: http://www.norizzang.org/
    -
        logo: woozoo.jpg
        title: WOOZOO
        description: Sharing house with those with similar hobbies and experiences. WOOZOO is a company that creates and provides shared houses. WOOZOO supplies housing to students at low cost, and helps residents share their hobbies and experiences with one another.
        homepage: http://woozoo.kr/
    -
        logo: hello_market.jpg
        title: Hello Market
        description: Small-scale flee market operated in a small open space for recreation, which is mandatory in buildings
        homepage: http://www.hellomarket.com/
    -
        logo: church.jpg
        title: Church Plus
        description: Linking with people who wish to use church space for weddings, etc.
        homepage: http://www.churchplus12.com/
    -
        logo: sss.jpg
        title: Seoul Social Standard
        description: Strives to propagate shared house models
        homepage: http://3siot.org/roundabout/
    -
        logo: spacecloud.png
        title: Space Cloud
        description: Information platform that connects people with spaces fitting their needs. It provides a list of variety shared space which could be rent comfortable with good price.
        homepage: http://spacecloud.kr
    -
        logo: spaceshare.png
        title: Space Share
        description: Providing variety informations about study rooms, meeting rooms and other space renting issues.
        homepage: http://spaceshare.kr/
    -
        logo: storesharing.png
        title: Store Sharing
        description: Store-sharing connects design teams who need spaces with the shop providing space to sell design objects. Sharing space revitalize existing retailers and help pioneer designers to find their way to start up.
        homepage: http://store-sharing.com/
    -
        logo: honghap.jpg
        title: Honghap Valley
        description: Honghap Valley is the plattforn where the worries of start-ups are solved. It incubates start-ups, ventures, preliminary founders and helps to build indigenous ecosystem.
        homepage: http://honghapvalley.org
    -
        logo: inoon.png
        title: ino-on
        description: As ino-on´s main project, Parking Plex provides IoT (Internet of Things) technology-based services to solve the parking problems through sharing parking spaces.
        homepage: http://www.parkingplex.co.kr
    -
        logo: cocofarms.png
        title: cocofarms
        description: cocofarms connect people with idle land and people want to tryout farming without owning their own land.
        homepage: http://www.cocofarms.co.kr
    -
        logo: gongdok.png
        title: Gongdok
        description: Through Gongdok you can find an empty seat in studyrooms which can be used freely throughout Seoul.
        homepage: http://www.gongdok.com

Object/Sharing:
    -
        logo: wonderland.jpg
        title: Wonderland
        description: Linking with people who wish to rent or borrow goods that are not used frequently, including travel luggage or bags
        homepage: http://wonderlend.kr/
    -
        logo: billi.jpg
        title: Billi
        description: Linking with people who wish to rent or borrow goods that are not used frequently, including travel luggage or bags
        homepage: http://billi.co.kr/
    -
        logo: billiji.jpg
        title: Billiji
        description: Linking with people who wish to rent or borrow goods that are not used frequently, including travel luggage or bags
        homepage: http://billiji.com/
    -
        logo: snu.jpg
        title: Super Natural Used Market
        description: Linking with people who wish to rent or borrow goods that are not used frequently, including travel luggage or bags
        homepage: http://cafe.naver.com/snumarket/125
    -
        logo: tikle.jpg
        title: Tikle
        description: Tikle is a sharing company that provides a carpool service. The service opened in May 2013, and there are now around 30,000 members actively engaging in the carpool as of June 2014. Tikle is a platform that connects people who want to carpool. Users can enjoy reasonable consumption and resource preservation using the Tikle service. 
        homepage: http://www.tikle.co.kr/
    -
        logo: nmarket.jpg
        title: N Market
        description: Linking with people who wish to share trivial jobs or work or rent or borrow goods that are not used frequently, including travel luggage or bags
        homepage: https://www.facebook.com/nmarketpage
    -
        logo: socar.jpg
        title: SoCar
        description: SOCAR is a socially innovative company that offers a flexible and reasonable alternative to private vehicle use by providing an economic and eco-friendly car sharing service. SOCAR was put in charge of Seoul&#39;s official car sharing service, Nanum Car, in March 2012, only one year after its foundation at Jeju in November 2011.
        homepage: http://www.socar.kr/
    -
        logo: greencar.png
        title: Green Car
        description: Green Car is the first and the biggest car sharing company in Korea. It was a groundbreaking moment for the company as brand awareness and trust in car sharing increased among citizens. Also, as the company was allowed to use public parking lots that are operated by the city, it is now able to provide a more accessible car sharing service.
        homepage: http://www.greencar.co.kr/
    -
        logo: car_sharing.jpg
        title: Car Sharing Korea
        description: Car sharing service that enables borrowing cars as required using smart phones
        homepage: http://www.wesharecar.co.kr/
    -
        logo: kiple.jpg
        title: Kiple
        description: KIPLE is a service that connects individuals wishing to exchange and share children’s wear that no longer fits in a fair and convenient manner. KIPLE conducts its children’s wear sharing business along with the regional community through collaboration with national and public nursing homes within Seoul’s boroughs.
        homepage: http://kiple.net/
    -
        logo: open_closet.jpg
        title: The Open Closet
        description: There are many young people currently in search of a job in Korea. And, in many cases, they are faced with the burdensome price of suits for their interviews. In July 2012, OPEN CLOSET began its clothing rental business for young people facing economic difficulty and people from socially neglected and vulnerable classes. Since its foundation, the business has enjoyed 5,000 trades and 450,000 cumulative visitors.  
        homepage: http://theopencloset.net/
    -
        logo: staff_seoul.jpg
        title: Staff Seoul
        description: Business that shares stage facilities or props abandoned after a show is over
        homepage: http://www.staffseoul.com/
    -
        logo: marketinu.jpg
        title: Market In U
        description: Community-oriented, cultural used-market Market In U practice buying, selling, exchanging, fostering, sharing goods and try to realize the virtuous cycle of resources.
        homepage: http://www.marketinu.com/
    -
        logo: twr.png
        title: Theater Waste Recycle (TWR)
        description: Theater Waste Recycle (TWR) is a window of communication of the community where you can exchange and recycle leftover stage props, sets.
        homepage: http://www.twr.or.kr/

Experience/Talent_sharing:
    -
        logo: myrealtrip.jpg
        title: My Real Trip
        description: myRealTrip provides a customized travel service accompanied by local people. Since the launch of the service in February 2012, approximately 18,000 people have travelled to 187 cities around the world using myRealTrip. There is a good reason behind many people’s use of the company’s service. Trust is the key to the travel service business, and the company was able to provide this trust due to its position as an official sharing company recognized by the Seoul Metropolitan Government. 
        homepage: http://www.myrealtrip.com/
    -
        logo: playplanet.jpg
        title: Play Planet
        description: Provides information on tourist destinations by linking tourists with a local guide
        homepage: http://www.letsplayplanet.com/ko/
    -
        logo: wisdome.jpg
        title: Wisdome
        description: Wisdome is a platform designed to enable ‘Human Books’ to share their knowledge, insight and know-how with people in need. Launched in March 2012, Wisdome presents around 1,000 people, collectively known as ‘Human Books’, who possess experience and stories from diverse fields. In the past two years, around 24,000 participants have held 2,500 meetings through Wisdome. 
        homepage:  http://wisdo.me/
    -
        logo: joinus.jpg
        title: Join Us Korea
        description: Community for sharing knowledge or multiple cultures in multiple languages for foreigners staying in Korea
        homepage: http://www.joinusworld.org/
    -
        logo: bookpr2.jpg
        title: Book PR Media
        description: Flash mob events organized to read books in subway stations or trains
        homepage: http://www.bookprmedia.com/
    -
        logo: wishket.jpg
        title: Wishket
        description: Linking programmers or designers with businesses or individuals for short-term service
        homepage: http://wishket.com/
    -
        logo: zipbob.jpg
        title: Zipbob
        description: Zipbab is an online platform dedicated to social dining. This innovative online solution provides services-including location brokerage, reservation, payment gateway and participant invitation-designed to enable anyone to conveniently host a meeting. The huge increase in one-person households has resulted in increased demand for communication and help with forming relationships help with forming relationships. 
        homepage: http://www.zipbob.net/
    -
        logo: itda.jpg
        title: Ready and Start
        description: Supports young people in realizing their dreams by sharing the experiences and wisdom of seniors
        homepage: http://www.ittda.co.kr/
    -
        logo: airklass.jpg
        title: AirKlass
        description: Sharing experiences and knowledge by displaying video clips of lectures on the Internet
        homepage:  http://www.airklass.com/
    -
        logo: local_design_movement.jpg
        title: Local Stitch
        description: The local hotel ‘Local Stitch’ is a platform that remodels small regional superannuated inns and provides an accommodation service while connecting guests with the tourism resources and services of a particular local community. The Local Stitch prototype model began on October 2013 in Seogyo-dong, Mapo-gu, Seoul. Using this prototype, the company is experimenting with whether it can provide a hotel-grade complex service through the sharing of regional services and contents. 
        homepage: http://www.localstitch.kr/
    -
        logo: epoom2.jpg
        itle: Eunpyeong e-Poomasi
        description: Allows local residents to share talents or goods using a local virtual currency
        homepage: http://poomasi.welfare.seoul.kr/community/CMMN31/upum_user_index.do
    -
        logo: quest_runner.jpg
        title: Questrunner Korea
        description: Supports the sharing of talents by providing a platform for linking people to temporary jobs
        homepage: http://www.questrunner.com/
    -
        logo: lingofly.png
        title: Lingofly
        description: Lingo fly will share the 70 million native talents around the world. Everyone could select a language to learn or to teach.
        homepage: http://www.lingofly.com/
    -
        logo: headflow.jpg
        title: Headflow
        description: The major projects of Headflow is Open College suggesting a new model of learning such as 'making together'.
        homepage: http://www.headflow.net/
